language: csharp
solution: "ProcessAnalyzerConsole.sln"

install:
- dotnet: 2.1.300

script:
- dotnet test ./packages/xunit.runners.*/tools/xunit.console.clr4.exe ./ProcessAnalyzerConsole/bin/Debug/ProcessAnalyzerConsole.dll
